### ISSUE TITLE
Not worked

### ISSUE THREAD

**Issue by xmoonlight** [wilminator/dokuwiki-plugin-twofactorgoogleauth#4]
I want make possible google two factor authentication on DokuWiki.

I'm installed your plugin https://www.dokuwiki.org/plugin:twofactor 
and i can't found/see this form: https://www.dokuwiki.org/lib/exe/fetch.php?w=160&tok=12c9e4&media=http%3A%2F%2Fi.imgur.com%2Fd0oeyOl.png 

I was installed all requirements:
1. https://www.dokuwiki.org/plugin:attribute 
Configuration path folder for attribute save is not correct: this folder must get "data" folder from main settings dokuwiki.
Current: "data/attributes"
Correct: "attributes": please, fix code for concatenate together path to "data" folder from main settings dokuwiki and subfolder "attributes" from plugin setting.

2. https://www.dokuwiki.org/plugin:twofactor

3. https://www.dokuwiki.org/plugin:twofactorgoogleauth 

My folders hierarchy from domain root folder:
  * data (is an "dokuwiki" data folder for better security: by [this link](https://www.dokuwiki.org/security#move_directories_out_of_docroot) from documentation)
  * public_html (is an "www-root")
    * book (is an "dokuwiki")
      * bin
      * conf
      * inc
      * lib
      * vendor

"public_html" is an "www-root"
"book" is an "dokuwiki"

Please help for resolve this and fix bugs.
Thanks a lot!

**Comment by Draky50110** [comment]
Solved in last twofactor plugin version (2018-06-20) : https://github.com/wilminator/dokuwiki-plugin-twofactor/issues/9

**Comment by wilminator** [comment]
Glad to hear this!

**Comment by xmoonlight** [comment]
@wilminator, I found Twofactor Management link ONLY after switch to "dokuwiki" template.

In ["vector" template](https://www.dokuwiki.org/template:vector) TwoFactor management link (`doku.php?id=start&do=twofactor_profile`) is not showing between "Manage" and "Profile" (as in "dokuwiki" template) in menu items (top-right corner).

Better: insert this functionality into user profile page (if is possible).

Could you fix this in the library code for any template?
Thanks.

**Comment by wilminator** [comment]
I don't want to add it to the user profile because this menu can become
large, and some wiki's do not give their users access to the profile (mine
is one of them).
As for the problem with the vector template, it might be that they do not
properly handle the addition of menu items.  That was the problem with the
bootstrap3 template.  I will take a look at the vector template and at
least identify the cause.  If the problem is not too difficult to fix, I
may supply a patch to the template moderator.  No promises though.

**Comment by xmoonlight** [comment]
@wilminator, OK. In any case, in advance, many thanks to you and I would like that this be fixed it (if it's possible) and without urgent time. Thank you!
