### ISSUE TITLE
No Two Factor configuration link at the upper right menu.

### ISSUE THREAD

**Issue by Xantion** [wilminator/dokuwiki-plugin-twofactorgoogleauth#5]
Hi,

I installed the plugin using the plugin manager, enabled the plugin in the config settings.
But the Two Factor Configuration page doesn't show. (Also not after relog)

With kind regards,

Mitchell

**Comment by wilminator** [comment]
Hello,
Please ensure that you have installed the Attribute plugin, the Main TwoFactor plugin, and at least one plugin with the security feature you are looking for.  If you have done this, please post which TwoFactor plugins you are using so I can setup my testing website.
Greetings,
Mike

**Comment by Xantion** [comment]
Awesome, it works!
Thanks.
