### ISSUE TITLE
Image can't be displayed

### ISSUE THREAD

**Issue by Draky50110** [wilminator/dokuwiki-plugin-twofactorgoogleauth#6]
Hello.

Using 2018-06-20 version of twofactor, I can't use GA auth because when clicking on the menu item , it tells me that the image can't be displayed.

Greebo, Firefox.

Any clue ?

Thanks.

**Comment by wilminator** [comment]
I don't know what that would be immediately. To clarify what is happening step by step, you see the menu link, you click on the link, and you get an error that the image cannot be displayed.  Is that message in a browser pop-up, or in the 2FA profile page? Also, can you confirm PHP version?

**Comment by Draky50110** [comment]
I click on the menu item, and then it displays the error message of image problem.
https://screenshots.firefox.com/GHA4WEdzqJH04rv8/www.parigotmanchot.fr for a screenshot
On Chrome, same problem : black page with nothing inside.
PHPInfo : https://gilles.wittezaele.fr/phpinfo.php
Do I need special PHP extensions enabled ?

**Comment by wilminator** [comment]
GD is installed, so that is not the problem.  Could you send me the output from https://www.dokuwiki.org/faq:version ? It might point me at where to look.

**Comment by Draky50110** [comment]
https://screenshots.firefox.com/rh0yX5zB9TZb1ns4/www.parigotmanchot.fr

**Comment by wilminator** [comment]
Was there any more to that output?  I was hoping to confirm the template you are using so that I can install it too.

**Comment by wilminator** [comment]
I have released an update to this module.  I used output buffer capturing to collect the image which could cause problems. I changed it over to something else, and I am hoping that it will solve your problem.  If it does not, we can still work on it.  I wanted to make this change anyway.

**Comment by Draky50110** [comment]
It works !
All is ok, scancode is displayed and so :)
Thanks a lot :)
